import type { FlatResourcePageContract } from '#/templates/resource/resource-page-contract';

const outcomeOptions = [
  { label: '成功', value: 'true' },
  { label: '失败', value: 'false' },
];

const readOnlyTable = {
  allowCreate: false,
  allowDelete: false,
  allowEdit: false,
};

export const operationLogPageContract: FlatResourcePageContract = {
  authorizationResource: 'operation.log',
  detailFields: [
    { field: 'occurred_at', label: '发生时间', presentation: 'datetime' },
    { field: 'operation', label: '操作' },
    { field: 'succeeded', label: '是否成功', presentation: 'boolean' },
    { field: 'duration_ms', label: '耗时（毫秒）' },
    {
      field: 'actor_id',
      label: '操作人',
      displayField: 'actor_name',
      presentation: 'reference',
    },
    { field: 'actor_type', label: '操作人类型' },
    { field: 'resource_type', label: '资源类型' },
    {
      field: 'resource_id',
      label: '资源',
      displayField: 'resource_name',
      presentation: 'reference',
    },
    { field: 'source', label: '来源' },
    { field: 'protocol', label: '协议' },
    { field: 'method', label: '方法' },
    { field: 'route', label: '路由', span: 2 },
    { field: 'client_ip', label: '客户端 IP' },
    { field: 'user_agent', label: 'User Agent', span: 2 },
    { field: 'request_id', label: 'Request ID' },
    { field: 'trace_id', label: 'Trace ID' },
    { field: 'error_code', label: '错误码' },
    { field: 'error_message', label: '错误信息', span: 2 },
    {
      field: 'request_payload',
      label: '安全请求摘要',
      presentation: 'json',
      span: 2,
    },
    { field: 'extension', label: '扩展信息', presentation: 'json', span: 2 },
  ],
  editorFields: [],
  queryFields: [
    {
      key: 'keyword',
      label: '关键词',
      placeholder: '操作、资源、操作人或 Request ID',
      type: 'keyword',
    },
    {
      filterKey: 'actor_ids',
      key: 'actor_ids',
      label: '操作人 ID',
      maxItems: 200,
      type: 'id-in',
    },
    {
      filterKey: 'operations',
      key: 'operations',
      label: '操作标识',
      maxItems: 200,
      type: 'id-in',
    },
    {
      filterKey: 'resource_types',
      key: 'resource_types',
      label: '资源类型',
      maxItems: 200,
      type: 'id-in',
    },
    {
      filterKey: 'resource_ids',
      key: 'resource_ids',
      label: '资源 ID',
      maxItems: 200,
      type: 'id-in',
    },
    {
      filterKey: 'request_ids',
      key: 'request_ids',
      label: 'Request ID',
      maxItems: 200,
      type: 'id-in',
    },
    {
      key: 'succeeded',
      label: '执行结果',
      options: outcomeOptions,
      type: 'boolean',
    },
    { key: 'occurred_at', label: '发生时间', type: 'date-range' },
  ],
  table: {
    ...readOnlyTable,
    columns: [
      {
        field: 'occurred_at',
        minWidth: 180,
        presentation: 'datetime',
        title: '发生时间',
      },
      { field: 'operation', minWidth: 220, title: '操作' },
      {
        field: 'actor_id',
        displayField: 'actor_name',
        minWidth: 170,
        presentation: 'reference',
        title: '操作人',
      },
      { field: 'resource_type', minWidth: 150, title: '资源类型' },
      { field: 'resource_name', minWidth: 170, title: '资源' },
      { field: 'duration_ms', minWidth: 110, title: '耗时(ms)' },
      {
        field: 'succeeded',
        minWidth: 90,
        presentation: 'boolean',
        title: '成功',
      },
      { field: 'request_id', minWidth: 220, title: 'Request ID' },
      { field: 'action', fixed: 'right', title: '操作', width: 90 },
    ],
    endpoints: {
      create: '/operation-logs/page',
      delete: '/operation-logs/page',
      get: '/operation-logs/get',
      page: '/operation-logs/page',
      update: '/operation-logs/page',
    },
  },
};

export const securityLogPageContract: FlatResourcePageContract = {
  authorizationResource: 'security.log',
  detailFields: [
    { field: 'occurred_at', label: '发生时间', presentation: 'datetime' },
    { field: 'event_type', label: '事件类型' },
    { field: 'succeeded', label: '是否成功', presentation: 'boolean' },
    { field: 'reason', label: '原因' },
    {
      field: 'actor_id',
      label: '操作人',
      displayField: 'actor_name',
      presentation: 'reference',
    },
    { field: 'actor_type', label: '操作人类型' },
    {
      field: 'subject_id',
      label: '目标主体',
      displayField: 'subject_name',
      presentation: 'reference',
    },
    { field: 'subject_type', label: '主体类型' },
    { field: 'client_ip', label: '客户端 IP' },
    { field: 'user_agent', label: 'User Agent', span: 2 },
    { field: 'session_id', label: '会话 ID' },
    { field: 'request_id', label: 'Request ID' },
    { field: 'trace_id', label: 'Trace ID' },
    { field: 'identifier_hash', label: '标识摘要' },
    { field: 'error_code', label: '错误码' },
    { field: 'error_message', label: '错误信息', span: 2 },
    { field: 'metadata', label: '扩展信息', presentation: 'json', span: 2 },
  ],
  editorFields: [],
  queryFields: [
    {
      key: 'keyword',
      label: '关键词',
      placeholder: '主体、会话、Request ID 或错误码',
      type: 'keyword',
    },
    {
      filterKey: 'actor_ids',
      key: 'actor_ids',
      label: '操作人 ID',
      maxItems: 200,
      type: 'id-in',
    },
    {
      filterKey: 'subject_ids',
      key: 'subject_ids',
      label: '主体 ID',
      maxItems: 200,
      type: 'id-in',
    },
    {
      filterKey: 'subject_types',
      key: 'subject_types',
      label: '主体类型',
      maxItems: 50,
      type: 'id-in',
    },
    {
      filterKey: 'event_types',
      key: 'event_types',
      label: '事件类型',
      maxItems: 50,
      type: 'id-in',
    },
    {
      filterKey: 'client_ips',
      key: 'client_ips',
      label: '客户端 IP',
      maxItems: 200,
      type: 'id-in',
    },
    {
      filterKey: 'request_ids',
      key: 'request_ids',
      label: 'Request ID',
      maxItems: 200,
      type: 'id-in',
    },
    {
      key: 'identifier',
      label: '登录标识',
      placeholder: '输入原始用户名或标识进行摘要匹配',
      type: 'text',
    },
    {
      key: 'succeeded',
      label: '执行结果',
      options: outcomeOptions,
      type: 'boolean',
    },
    { key: 'occurred_at', label: '发生时间', type: 'date-range' },
  ],
  table: {
    ...readOnlyTable,
    columns: [
      {
        field: 'occurred_at',
        minWidth: 180,
        presentation: 'datetime',
        title: '发生时间',
      },
      { field: 'event_type', minWidth: 220, title: '安全事件' },
      {
        field: 'actor_id',
        displayField: 'actor_name',
        minWidth: 170,
        presentation: 'reference',
        title: '操作人',
      },
      {
        field: 'subject_id',
        displayField: 'subject_name',
        minWidth: 170,
        presentation: 'reference',
        title: '目标主体',
      },
      { field: 'client_ip', minWidth: 140, title: '客户端 IP' },
      {
        field: 'succeeded',
        minWidth: 90,
        presentation: 'boolean',
        title: '成功',
      },
      { field: 'request_id', minWidth: 220, title: 'Request ID' },
      { field: 'action', fixed: 'right', title: '操作', width: 90 },
    ],
    endpoints: {
      create: '/security-logs/page',
      delete: '/security-logs/page',
      get: '/security-logs/get',
      page: '/security-logs/page',
      update: '/security-logs/page',
    },
  },
};
